sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tejas-niturkar/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true tejas-niturkar/docker-react npm run test

deploy: 
  provider: elaticbeanstalk
  region: "ap-south-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-973786695283"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

