sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tejas-niturkar/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true tejas-niturkar/docker-react npm run test
